### PR TITLE
Add abbreviations to all books

### PR DESCRIPTION
**Pull request by xinthose**
Hello,

I would like to make this repository more developer friendly rather than just a collection of JSON files.  I added gulp to allow minifying the source and added a separate source directory with the JSON formatted for human reading / editing.  I added a change log and installation instructions as well.  I also added lookup files that are used in my website and could be useful for other developers (took me a long time to create): http://www.xinthose.com/bible.  

Besides thiagobodruk's [repo](https://github.com/thiagobodruk/bible), this is the 2nd best IMO.  I only use the KJV.  thiagobodruk has not been maintaining his repository, so here I am.

TCGB

### CODE REVIEW

**Comment by RClickDev** [comment]
Hi @xinthose well done, I will be going with your implementation. who knows we could work on it some more and make it more developer friendly.

**Comment by xinthose** [comment]
@aruljohn do you want to merge this PR?

**Comment by aruljohn** [comment]
> @aruljohn do you want to merge this PR?

@xinthose, thank you for all the work you did on this and the kind comments. I would like my repo to stay as a simple collection of JSON files in its current form without the extras. Your additions will be very useful to many developers. Please continue to maintain your fork. Thanks and God bless!

**Comment by xinthose** [comment]
@aruljohn Roger.

**Pull request closed without merging**
